package pwcg.campaign.skirmish;

public enum SkirmishProfileType
{
    SKIRMISH_PROFILE_PARA_DROP,
    SKIRMISH_PROFILE_CARGO_DROP,
    SKIRMISH_PROFILE_ANTI_INFANTRY,
    SKIRMISH_PROFILE_ANTI_SHIPPING,
    SKIRMISH_PROFILE_ANTI_RIVER_TRAFFIC,
    SKIRMISH_PROFILE_ANTI_RAIL,
    SKIRMISH_PROFILE_AIRFIELD,
    SKIRMISH_PROFILE_CARPET_BOMB,
    SKIRMISH_PROFILE_INVASION
}
