package pwcg.campaign.skirmish;

public enum SkirmishProfileType
{
    SKIRMISH_PROFILE_PARA_DROP,
    SKIRMISH_PROFILE_CARGO_DROP,
    SKIRMISH_PROFILE_ANTI_ARMOR,
    SKIRMISH_PROFILE_ANTI_SHIPPING,
    SKIRMISH_PROFILE_ANTI_RIVER_TRAFFIC,
    SKIRMISH_PROFILE_ANTI_RAIL,
    SKIRMISH_PROFILE_AIRFIELD
}
