package pwcg.mission.ground.org;

public enum GroundUnitCollectionType
{
    INFANTRY_GROUND_UNIT_COLLECTION,
    BALLOON_GROUND_UNIT_COLLECTION,
    TRANSPORT_GROUND_UNIT_COLLECTION,
    STATIC_GROUND_UNIT_COLLECTION,
}
