package pwcg.mission.flight.waypoint.missionpoint;

public enum MissionPointSetType
{
    MISSION_POINT_SET_ACTIVATE,
    MISSION_POINT_SET_BEGIN_AIR,
    MISSION_POINT_SET_BEGIN_TAKEOFF,
    MISSION_POINT_SET_BEGIN_VIRTUAL,
    MISSION_POINT_SET_ATTACK,
    MISSION_POINT_SET_ESCORT,
    MISSION_POINT_SET_ROUTE,
    MISSION_POINT_SET_RENDEZVOUS,
    MISSION_POINT_SET_END, MISSION_POINT_SET_DELAY;
}
